name: CI

on:
  push:
    branches: [split_parser]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test parsers
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Build with all extensions
        run: node scripts/build.js
        env:
          ALL_EXTENSIONS: 1
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-rust: true
          test-parser-cmd: node scripts/test.js
      - name: Rebuild with default extensions
        run: node scripts/build.js
      - name: Verify grammar consistency
        run: git diff --exit-code -- */src/grammar.json
