name: Create release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@7e826c707144002b73b91d2ac9952e6fff03dc5b
    with:
        attestations: true
